### ISSUE TITLE
MIS TAREAS: Falla funcionalidad del botón ordenar/filtrar ⇅

### ISSUE THREAD

**Issue by fhernandez-trazalog** [Trazalog/traz-prod-assetplanner#130]
Ambiente test - v2.6.4

**Descripción**
Al querer ordenar, considerando como filtro cualquiera de las columnas, podemos observar en la pantalla que dice "cargando" y luego no hace nada. Adjunto imagen alusiva:

![Captura de pantalla (3390)](https://github.com/Trazalog/traz-prod-assetplanner/assets/136350470/3ab844d9-6779-4baf-92e2-2498afe342ff)

**Pasos a reproducir:**
1. Mis tareas
2. Click en botón "⇅"
3. Alterar el orden de los factores, de acuerdo al criterio de la columna posicionada

**Comment by floto-trazalog** [comment]
Ambiente test - v2.7.7

**Descripción:**
Continúa la falla, con la diferencia que carga la tabla pero no muestra el filtrado

URL: http://10.142.0.16/test_v2/traz-prod-assetplanner/
Se ha probado con el usuario: suptest1 | pass: 123

Se agrega un video demostrativo

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/ef3a27c3-cf72-4015-9ed5-0f16aeb613f5

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
