### ISSUE TITLE
SOPORTE-->Bandeja de tareas: que actualice automáticamente la bandeja de tareas

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#155]
Ambiente Test - v2.6.6

**Descripción:**
Se recomienda agregar una recarga automática en la bandeja de tareas, para que el usuario no tenga que recargar constantemente

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/82d9344c-d1ff-451d-9c34-70b72536c6f8)

**Nota:**
Que esta mejora se aplique a todos los usuarios

**Comment by floto-trazalog** [comment]
### RENOVACIÓN DEL ISSUE

Se recomienda agregar un botón llamado "Actualizar" de la página de la Bandeja de tareas, que sea similar al que se muestra en la imagen

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/f9954fa3-8e14-4462-aeca-7ecb101c02e8)

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by rodolfo-ruiz-rtools** [comment]
@pmarrelli-trazalog que actualice automaticamente cada X segundos configurables si
 - no hay nada filtrado
 - no esta paginado

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.5
