### ISSUE TITLE
SOPORTE-->Mantenimiento-->Solicitud de servicio: visualizar al “Mantenedor” que tomó la tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#177]
Ambiente Test - v2.6.9.1

**Mejora:**
Se recomienda agregar una columna a la izquierza de los estados y que se visualice el “Mantenedor” que tomó la tarea de la solicitud

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/17ba4f84-eccc-4efa-a2d8-75078b045f03)

El nombre se recupera de la selección mostrada en la siguiente imagen

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/965ff979-9dcf-48d5-ae32-b6570da40d9b)

**Pasos a seguir:**
1. En Mantenimiento
2. Clic en Solicitud de Servicio

**Comment by jfernandez-trazalog** [comment]
Pablo M.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.5
