### ISSUE TITLE
Mantenimiento --> Plan de mantenimiento: Agregar notificacion de tareas programadas

### ISSUE THREAD

**Issue by gnicolia-trazalog** [Trazalog/traz-prod-assetplanner#182]
Ambiente de test- v 2.7

Mejora: Se recomienda agregar notificaciones de aviso en las tareas programadas recien guardadas en el calendario. 

![image](https://github.com/Trazalog/traz-comp-almacenes/assets/146888657/b8f75397-f84a-46d7-a5cb-c7eacc4a8353)

Pasos a seguir: 

1. Mantenimiento
2. Plan de mantenimiento
3. Solapas de tareas

**Comment by floto-trazalog** [comment]
Se cierra puesto que las notificaciones se encuentran desarrolladas
