### ISSUE TITLE
SOPORTE-->Mantenimiento-->Plan de Mantenimiento: resaltar las tareas que aún no se han asignado 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#185]
Ambiente test - v2.7.1

**Mejora:**
Se recomienda resaltar las tareas que figuran en el calendario que aún no se han asignado

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/9454f1d3-2a49-414d-b800-99519cbde809)

**Pasos a seguir:**
1. En Mantenimiento
2. Plan de Mantenimiento
3. En Calendario

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Casi solucionado.

- Se recomienda aplicar el resaltado en todas las tareas existentes, tanto en `predictivos`, `preventivos`, `solicitud_reparacion`, `backlog` y `orden_trabajo`

 **Detalles adicionales:**
- **Impacto:** Este problema afecta la eficacia de los usuarios para encontrar tareas urgentes y sin asignar, puesto que en un día se llegan a registrar más de 30 tareas.

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/bb2894bb-5887-48e5-8e72-e044f71603ac



- **Esperado:** 
Se espera que el sistema sea eficaz y accesible en los momentos de alta concurrencia

**Entorno de trabajo**: Ambiente test - v2.7.5

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.7
