### ISSUE TITLE
Mantenimiento-->Solicitud de servicio: permite guardar sin completar el campo obligatorio

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#188]
Ambiente Test - v2.9.1

**Descripción:**
Al completar el campo "Sector" y dejar el campo obligatorio "Equipo" vacío, el sistema permite guardar sin validar dicho campo y la tarea se graba, pero no figura en el listado de registros de la pantalla de Solicitud de servicios
(se adjunta video con audio)

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/dfab3f43-47f6-44a6-b015-696afc807a0d

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/31d4aea6-5d45-457b-9fd9-8eaeb3fff0dd)
 
y al revisar en la base de datos el sistema lo guarda con ID = -1

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/1c25951b-1ee5-49aa-8c46-4b81609f2553)

Lo correspondiente sería que el sistema valide que los campos obligatorios estén completos para luego grabar el registro, de lo contrario se debe notificar al usuario con el siguiente aviso:

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/5e35cbf2-7741-4c08-ad5c-a8ce74f8b6b6)
 
**Pasos a seguir:**
1. En Mantenimiento
2. Solicitud de servicio
3. Completar el campo "Sector" 
4. Clic en el botón "Guardar"

**Comment by lzorrilla-trazalog** [comment]
Ha sido, resuelto... Hemos validado que los campos requeridos esten con datos y no vacios, -1 o null.

**Comment by floto-trazalog** [comment]
Solucionado v2.7.3
