### ISSUE TITLE
(DEMI) Prio 1-->Almacenes-->Artículos: eliminar el registro de la base de datos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#191]
Ambiente Producción 

**Descripción:**
Eliminar el registro de la base de datos de los artículos con los códigos Nro.: "1406" y "1407". Puesto que han sido objeto de demostraciones para capacitar y luego serán requeridos para artículos con la codificación mencionada y la misma no estará disponible. 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/dbf548ca-17b5-4fd6-a2b8-adf14797b6fe)

**Pasos a seguir:**
1. Almacenes
2. Artículos

**Comment by lzorrilla-trazalog** [comment]
Eliminados de base de datos los artículos con los códigos Nro.: "1406" y "1407"

**Comment by floto-trazalog** [comment]
Se cierra puesto que el cliente DEMI ya se encuentra inactivo
