### ISSUE TITLE
SOPORTE-->Escritorio-->KPI's: que los gráficos muestren el promedio por sector

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#195]
Ambiente Test - v2.9.1

**Mejora:**
Al completar los filtros seleccionando el Sector "Boxer" e ingresar la fecha desde abril hasta octubre, los gráficos muestran valores altos elevados, como si estuviera sumarizando las horas totales de todos los equipos. Y lo correspondiente, sería que muestre el promedio en horas.

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/44529f33-de3b-4f28-a553-c13f34936909)

**Pasos a seguir:**

1. Seleccionar el Sector: "Boxer"
2. Seleccionar fecha desde: 01/04/2023
3. Seleccionar fecha hasta: 31/10/2023
4. Clic en el botón "Filtrar"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.7
