### ISSUE TITLE
SOPORTE-->Manteniemiento-->Solicitud de Servicio: agregar columna del tiempo de asignación

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#197]
(Planificador) 

**Descripción:**
En el menú **Solicitud de Servicio,** 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/77b2efc1-03dd-4254-984b-8fa64616d14c)

agregar una columna llamada "Tiempo de Asignación" en donde se refleje el tiempo en unidad de _Horas_ transcurrido entre la asignación de la solicitud y el momento en que el _Mantenedor_ da clic en el botón "Iniciar tarea".

Momento de Asignación - Rol del Supervisor/Planificador

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/a0df6738-6d68-4b52-a920-5fc7bb73fcf1)

**Pasos a reproducir:** 

1. Paso previo, cargar una solicitud de servicio y asignarla como _Urgente_
2. En Mantenimiento
3. Plan de mantenimiento
4. Solapa "Solicitudes de servicio"
5. Clic en Generar OT de la tarea en cuestión
6. Asignar tarea desde el calendario

Momento de Inicio de tarea - Rol del Mantenedor

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/f145b429-25c4-485d-80af-1633223d7249)

**Pasos a seguir:**
1. En bandeja de tareas
2. Seleccionar tarea "Ejecutar OT"
3. Botón "Iniciar tarea"

**Comment by jfernandez-trazalog** [comment]
Luis Zorrilla.

**Comment by floto-trazalog** [comment]
Solucionado, pero con mejoras. en issue #229
