### ISSUE TITLE
Bandeja de tareas: que se visualice el archivo desde una pantalla smartphone

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#199]
Ambiente Test - v2.9.1

**Descripción:** Relacionado con incidencia #180 
Es requerimiento esencial que el archivo .pdf se pueda visualizar desde una pantalla del tamaño de un smartphone, puesto que el usuario final, en este caso, el mantenedor es quien realiza los registros desde dicho dispositivo 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/acc03566-ff8d-4cfc-ab01-e97014ba0a81)

**Comment by jfernandez-trazalog** [comment]
No está solucionado en la versión actual de ASSET v2.8.

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.9
