### ISSUE TITLE
Bandeja de Tareas (Mantenedor): que figure la "Vista Global" en la solapa de la tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#212]
Ambiente Test - v2.7.3.1

**Descripción:**
Cuando el mantenedor selecciona y toma la tarea el sistema solo muestra la solapa de tareas, lo correspondiente es que se muestren las 3 solapas: _Tareas_ | _Comentarios_ | _Vista Global_

**Nota:** se agrega captura de video

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/def5a84b-9b4a-4b1e-a5a9-aa88992ac519

**Comment by jfernandez-trazalog** [comment]
No está solucionado en la versión actual de ASSET v2.8.

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado. Ha sido un error de configuración.
