### ISSUE TITLE
SOPORTE-->Mantenimiento-->Ordenes de trabajo: falla al aplicar los filtros

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#218]
Ambiente de DEMO - v2.2.4.1

**Descripción:**
Al completar los campos del filtro y dar clic en el botón "Filtro" el sistema no muestra ningún registro de las tareas que se encuentran agregadas como solicitudes de servicios

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/d16937e4-0a3a-4316-a20d-7e650446aa9d

**Pasos a seguir:**
1. En Mantenimiento
2. Ordenes de trabajo
3. Seleccionar un Equipo (opcional: seleccionar un Estado)
4. Clic en botón "Filtrar"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
