### ISSUE TITLE
SOPORTE-->Reportes-->Rep Ordenes de trabajo: que recupere los registros correspondientes

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#220]
Ambiente DEMO - v2.7.4.1

**Descripción:**
Al filtrar por un campo, por ejemplo, Equipo o por Fechas, el sistema no recupera los registros respecto de lo solicitado siendo que hubo movimientos en el sistema en los que deberían visualizarse en la tabla.

  
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/503e4dc4-4a6d-4830-8542-c40af9bb4d81)

se muestran algunos de los movimientos con el equipo seleccionado en el reporte que se muestra en la img de arriba

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/4ca99504-7972-404e-a51f-77bc94aaccb7)

**Pasos aseguir:**
1. En Reportes
2. Rep Ordenes de trabajo
3. Seleccionar un Equipo (o ingresar Fechas desde y hasta)
4. Clic en el botón "Consultar"

**Comment by jfernandez-trazalog** [comment]
ACTUALIZACIÓN: Ambiente DEMO - v2.7.7.

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
