### ISSUE TITLE
SOPORTE-->Manteniemiento-->Solicitud de Servicio: agregar columna del tiempo de generación de dicha tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#222]
Ambiente test - v2.4.1

**Descripción:**
Al guardar una nueva “Solicitud de Servicio” 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/95bfe158-fdc7-40ea-a324-3be65f5040aa)

se sugiere agregar una columna llamada "Tiempo de Generación" y recupere el tiempo transcurrido desde que se generó la solicitud de servicio hasta que se asignó la misma y la unidad de tiempo deberá ser presentada en unidad de Horas

Nueva Sol. de servicio - Rol del Supervisor/Planificador

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/c6dfa61e-ddef-49a4-b8fc-101622acb67d)

Momento de Asignación - Rol del Supervisor/Planificador

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/b277d902-a866-4d57-b27b-47875e2464a2)

**Comment by jfernandez-trazalog** [comment]
Luis Z.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.5
