### ISSUE TITLE
SOPORTE-->Mantenimiento-->Solicitud de Servicio: agregar un botón que recupere u oculte los registros de estado "Conforme"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#223]
Ambiente Test - v2.7.4.1

**Descripción:**
Se recomienda agregar un botón con el título "Mostrar solicitudes conformes" entonces, cuando está inhabilitado solo muestra los registros en progreso, estado =! Conforme (_img 1_) y; al clickear en el botón (_img 2_), que muestre todos los registros

        Img 1

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/369d208d-e754-4089-836f-197f91a4434b)

        Img 2

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/0c6b8e33-1fbd-41c2-894c-e549ed4f7c16)

Cuando se ingresa a la vista deben aparecer las solicitudes de servicio con los siguientes estados 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/b9627c40-c9c8-4bd4-ac12-eae03f69e7a3)

y al hacer clic en el switch deben aparecer solamente las que tienen estado = Conforme "CN"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.7
