### ISSUE TITLE
Bandeja de tareas-->Cabecera: agregar la campana de notificación

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#226]
Ambiente test - v2.7.4.1

**Descripción:** se recomienda agregar la campana como figura en el sistema de Tools, se deja la imagen a modo de ejemplo, ubicada al lado de la imagen del perfil del usuario

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/f190968c-0919-416c-b14a-80de014fc128)

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/5062f673-493d-4e33-bd4a-ae84dd7428cd)

La funcionalidad de la campana de notificación es para informar de forma instantánea al usuario de que las transacciones que ocurren dentro de su Bandeja de Tareas, pro ejemplo: recibir una tarea nueva para ejecutar

**Comment by jfernandez-trazalog** [comment]
Luis Z.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
