### ISSUE TITLE
Mis tareas: re ubicar la columna "tipo tarea" al comienzo de la tabla

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#227]
Ambiente Test - v2.7.5

**Descripción:**
Se recomienda colocar la última columna agregada "Tip. Tarea" al comienzo de la tabla como se muestra en la imagen 

**Impacto:**
Es impráctico para el usuario final, puesto que se ejecuta el sistema desde un smartphone

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/49857a7b-da68-4ba1-a956-4dd44cbd5ea0)

**Esperado:**
Se espera que el usuario final, el mantenedor, al abrirse la Bandeja de tareas, detecte las tareas según su prioridad, desde la vista de un smartphone

**Comment by jfernandez-trazalog** [comment]
Rogelio Sanchez.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.7
