### ISSUE TITLE
Mantenimiento-->Preventivos: defecto en el front, re-ubicar el campo "Cantidad operarios" 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#228]
Ambiente TEST - v2.7.5

**Descripción:** Relacionado con issue #167 
Se sospecha que al agregar la modificación de los campos input por select se ha detectado un defecto en el front de la sección "programación", se ha bajado el campo: "cant. de operarios", como se muestra en la imagen

> Detalles adicionales

**Impacto:**
Esto genera confusión en el usuario ya que no se entiende qué valor ingresar

**Reproducción del error:**
1. En el menú, clic en Mantenimiento
2. Clic en el submenú "Preventivos"
3. Clic en el botón "Agregar"
4. Deslizar la pantalla hasta el sector de título:  _Programación_

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/00d640c4-6970-4bf5-af64-89f656ff3568)

**Esperado:**
Se espera que el diseño se mantenga unificado como se indica en la parte inferior de la imagen

Entorno de trabajo: Ambiente Test - v2.7.5

**Comment by jfernandez-trazalog** [comment]
Rogelio Sanchez.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.7
