### ISSUE TITLE
ABM -->ABM Clientes: quitar el botón "Cerrar"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#230]
Ambiente Test - v2.

**Descripción:**
Se recomienda quitar el botón "Cerrar" de la pantalla de ABM Clientes, puesto que no tiene ninguna funcionalidad

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/9133d217-5c70-40b8-9234-df01e69279a5)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
