### ISSUE TITLE
Mis Tareas (mantenedor)-->Tarea: Confección de Inf. de Servicio

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#231]
Ambiente DEMO - v2.7.7

**Descripción:**
Cuando el "mantenedor" de la empresa NOVU, completa el informe de servicio, en la última solapa llamada:  _Insumos_, el sistema recupera varios pedidos de materiales de la empresa TEST, (imagen adjunta) y lo correspondiente, en este caso particular, es que no muestre ningún pedido.
Que se recupere, únicamente, si se ha solicitado algún insumo, de lo contrario no debería mostrar ningún artículo.

> Detalles adicionales

**Impacto:**
La falta de sincronización entre la Planificación de la Orden de Trabajo (OT) y la Confección del Informe de Servicio pueden llevar a la confusión del usuario al momento de completar dicha tarea.

**Reproducción del error:** (loguearse con el usuario mantenedor)
1. Mis tareas: "Confección de Informe de servicio"
2. Completar el "Informe de Servicio" 
3. Elegir la última solapa "Insumos"

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/2a69fb3b-8baf-4c68-85ec-8e8a84307b26)

**Resultado esperado:** 
Se espera que al abrirse la ventana del "Informe de Servicio" recupere los pedidos asociados a dicha orden de trabajo, de lo contrario, no debería registrar datos.

**Entorno de trabajo**: Ambiente de DEMO - Empresa NOVU 
**URL:** https://demo.cloudtrazalog.com/tools/traz-prod-assetplanner/
**Usr:** mantenedor@novu.com
**Pass**: 12345
--
Empresa TEST
**Usr:** supervisor.mant
**Pass**: 123
--
**Observación:** en ambiente Test no está sucediendo

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
