### ISSUE TITLE
Mantenimiento-->Solicitud de servicio: que recupere el tiempo entre la asignación y el inicio de la tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#232]
Ambiente Test - v2.7.7 

**Descripción:**
En “Solicitud de Servicio”: se requiere visualizar el tiempo transcurrido entre la asignación de la solicitud y el inicio de la tarea por parte del “Mantenedor”

> Detalles adicionales ¬

**Impacto:**
Esta información es de vital importancia para el Planificador, puesto que le brinda eficiencia al momento de realizar las contabilizaciones de los tiempos 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/89b666a9-a530-443b-ad47-ca7886c7f8e3)

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/ccf6cf18-a9c4-4d31-8bc1-8d3ee806ff2e)

**Reproducción del error:**
1. En Mantenimiento
2. Solicitud de servicio
3. Crear una nueva solicitud "urgente"-->Planificarla-->**Asignarla (Planificador)**-->**Iniciar tarea (mantenedor)**

**Resultado esperado:**
Al momento de abrir el menú de Solicitud de servicio, que se muestre en la tabla el lapso de tiempo desde que el Planificador Asigna la OT al mantenedor hasta que este presiona el botón "Iniciar Tarea"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.
