### ISSUE TITLE
Mantenimiento-->Solicitud de servicio: que recupere el tiempo entre la creación de la Solicitud de Serv. y la asignación de la tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#233]
Ambiente Test - v2.7.7

**Descripción:**

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/10dddadd-680a-45ce-a347-490d71e2bb3d)

En **Solicitud de Servicio**, en la columna de "T. Generación" se requiere visualizar el tiempo entre la creación de la Solicitud de Servicio y la asignación de la tarea por parte del “Planificador”

> **Detalles adicionales** ¬

**Impacto:**
Esta información es de vital importancia para el Planificador, puesto que le brinda eficiencia al momento de realizar informes de  producción.

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/c0eec7bf-c325-4f7e-8732-e2b8578e6769)

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/7076c3d7-042d-4d9b-a5f5-695f874c6376

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/c50e0368-5046-4c36-ba19-0244672f80ea)

**Reproducción del error:**

1. En Mantenimiento
2. Solicitud de servicio
3. Crear una nueva solicitud "urgente" (Solicitante)-->Planificarla-->Asignarla (Planificador)

**Resultado esperado:**
Al momento de abrir el menú de Solicitud de servicio, que se muestre en la tabla el lapso de tiempo desde que el _Solicitante_ `crea y guarda` la tarea **hasta** que el _Planificador_ `Asigna la tarea`

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
