### ISSUE TITLE
Mantenimiento-->Solicitud de servicio: que permita agregar una nueva solicitud de servicio

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#236]
Ambiente DEMO - v2.7.7

**URL**: https://demo.cloudtrazalog.com/tools/traz-prod-assetplanner/
**Usr:** admin@novu.com
**pass:** 12345

**Descripción:**
Al crear una nueva solicitud de servicio, completar los campos obligatorios y presionar el botón "Guardar" el sistema muestra un cartel de error "_Falla: Error al Inciar Proceso_"

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/8b3a16d8-7012-4534-be00-25a0319fbcc4

**Impacto de la Falla:**
* Frustración del usuario
* Pérdida de información
* posibles errores adicionales

**Reproducción del error:**
1. En el menú "Mantenimiento"
2. Clic en Solicitud de Servicio
3. Clic en el botón "Agregar"
4. Completar los campos obligatorios
5. Clic en el botón "Guardar"

**Esperado:** que se grabe correctamente la solicitud de servicio y el registro correspondiente

**Entorno de trabajo**: Ambiente DEMO - v2.7.7

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado, fue un error de configuración de permisos.
