### ISSUE TITLE
SOPORTE-->Almacenes: configurar usuario para proceso de stock de insumos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#237]
Ambiente Producción - v2.7.7

URL: https://www.cloudtrazalog.com/tools/traz-prod-assetplanner/
usuario: planman@lacoste.com
pass: 12345

**Descripción:**
El cliente solicita que se le asigne los roles correspondientes para interactuar con el módulo Almacenes. Para ello se requiere habilitar los siguientes roles en el usuario planman@lacoste.com:

*  _Responsable de almacen_  
* _Solicitante de almacen_
* _Responsable de procesos_
* _Planificador de Tareas_ 
* _Responsable de Lote_
* _Responsable de Pañol_ 
* _Responsable de Producción_

> Actualmente, solo cuenta con los roles de:
> 
> Planificador de Mantenimiento Lacoste  
> &
> Supervisor de Mantenimiento Lacoste

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en en ambiente de producción y misma versión.
