### ISSUE TITLE
SOPORTE-->Almacenes-->Artículos: eliminar artículo desde la base de datos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#238]
Ambiente Producción de Lacoste - v2.7.7

URL: https://www.cloudtrazalog.com/tools/traz-prod-assetplanner/
Usr: admin@lacoste.com
pass: 12345

**Descripción:**
Se solicita eliminar el artículo que se indica más abajo desde la base de datos, porque el cliente lo ha borrado desde el sistema y se ha hecho un eliminado lógico por lo que no permite volver a agregarlo puesto que se repite el mismo código
Ahora, el cliente, requiere que sea quitado por completo del sistema para que pueda agregarlo nuevamente.

Código: Z00000130
Descripción: 70/10 RG 135x17 Botonera - Atracadora - Alegoría - de Campo

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Se cierra, porque se ha corregido la funcionalidad del botón "Editar"

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
