### ISSUE TITLE
SOPORTE-->Mantenimiento-->Solicitudes de servicio: falla visual en los títulos, que la pantalla sea responsive

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#239]
Ambiente Test - v2.7.7

**Descripción:**
Al ingresar al sistema desde una tablet, en el menú de Mantenimiento y seleccionar "Solicitud de servicio", se abre la página correctamente, pero los títulos se apilan al lado izquierdo de la tabla. (Como se ve en la imagen)

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/7a36ebbc-d8a9-4474-90dd-66e41ee463d4)

Luego, para acomodarlos, el usuario debe dar clic en el botón "Ordenar" de alguno de los títulos. (Como se muestra en el video), el dilema es que no lo saben todos los usuarios, solo algunos.

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/8acb7e58-01c9-4a3c-817f-fde41f84c190

> Detalles adicionales

**Impacto:**
Genera descontento en el usuario final ya que no puede visualizar correctamente los datos de la tabla.

**Respuesta esperada:**
Que el sistema recupere las tablas con los títulos ordenados por defecto, por ejemplo, con la columna "Nro" (en orden DESC). Es decir, que el usuario no tenga que dar "ese" clic para que se acomoden los títlos.

**Pasos a reproducir:** _(Recomendación: visualizar desde un emulador de tablet o tablet)_
1. En Mantenimiento
2. Clic en Solicitud de servicio

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
