### ISSUE TITLE
SOPORTE-->Mis tareas: eliminar el proceso de tareas vacías

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#240]
Ambiente de Producción - v2.7.7

**Descripción:**
Se recomienda eliminar el proceso de las solicitudes que figuran en la bandeja de tareas sin Equipos asignados. Dichas tareas se encuentran bajo el nombre "Análisis de solicitud de servicio" y "Planificar Solicitud", básicamente son todos los registros que se ven en la página 1 y los últimos 7 de la pág. 2.
(son las que se indican en las imagenes). 

Para visualizar las tareas en cuestión, se debe:
1. Ingresar al
URL: https://www.cloudtrazalog.com/tools/traz-prod-assetplanner/
2. Ingresar el usuario: planman@lacoste.com y la contraseña: 12345
3. Dirigirse al menú "Mis Tareas"

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/3b51c244-6842-4204-bc20-661b453d5539)

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/5ef93ab4-d748-4918-bf1a-b324cbefa3cc)

> Detalles adicionales:
**Resultado esperado:**
Que figuren únicamente en la bandeja de "Mis tareas" todas aquellas solicitudes en las que se han registrado los respectivos Equipos, Sector, Cliente y Descripción. Y las que no tienen Nro. de Solicitud de Servicio que dejen de figurar.

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
