### ISSUE TITLE
SOPORTE-->Bandeja de tareas: Quien tome una tarea que fue soltada por otro “Mantenedor”, al finalizarla pueda generar el Informe de Servicio de la tarea tomada y realizada.

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#241]
Ambiente Test - v2.7.7

**Descripción:**
Cuando se le asigna una tarea al Mantenedor 1 (M1) y luego, este mantenedor suelta la tarea y la toma el Mantenedor 2 (M2); al Terminar dicha tarea, el sistema lanza desde el Bonita una nueva tarea llamada "Confeccionar Informe de servicio" y le figura al M1, salvo que el M1 la suelte, el soft no permite que la complete el M2, quien complete

> **Detalles adicionales:**
**Impacto:**
Esto retrasa el flujo de producción porque los mantenedores deben notificarse por otro medio y para ellos es esencial optimizar el tiempo.

**Resultado esperado:**
Que el mantenedor que toma la tarea y la termina, tenga el permiso para continuar el proceso y finalizar el circuito de la solicitud de servicio.

**Pasos a seguir:**
1. Previamente, crear una nueva Solicitud de Servicio
2. Planificar la tarea y Asignarla a un usuario (mantest1)
3. Luego, mantest1 la suelta y, la toma mantest2
4. Finalizar la tarea con el usuario mantest2

(Video con audio)
https://drive.google.com/file/d/12PYeDOJKF9Mp8q5hDHUL_t5Qcfz3UlYn/view?usp=drive_link

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
Cumplido satisfactoriamente.
