### ISSUE TITLE
SOPORTE-->Almacenes-->Artículos: que permita registrar un nuevo artículo con un código que ya se ha ingresado

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#242]
Ambiente Test - v2.7.7

**Descripción:**
(relacionado al issue #238)
Al eliminar un artículo, el sistema no permite guardar nuevamente un nuevo artículo con un código que ya ha sido registrado

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
Observaciones: 
- No permite crear un artículo con un código que ya existe o existió (fue eliminado).
- No alerta cuando se intenta crear un artículo que ya existe.

**Comment by floto-trazalog** [comment]
Se decidió ocultar el botón de acción"Eliminar" puesto que no es una buena práctica agregar un nuevo registro con el código repetido.
