### ISSUE TITLE
SOPORTE-->Bandeja de tareas: actualizar el usuario "Asignado" por el user que tomó la tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#243]
Ambient Test - v2.7.7

**Descripción:**
(Relacionado al issue #241)
Cuando el mantenedor asignado suelta la tarea y la toma otro usuario mantenedor, el sistema no actualiza el nombre de usuario en la columna de la tabla de la Bandeja de "Mis Tareas" 

**Resultado esperado:** que figure el nombre del usuario que tomó la tarea.

En este caso, debería indicar en la columna el usuario _mantest2_
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/98859541-3f37-4f27-bf76-50926d9a7016)
 
https://drive.google.com/file/d/10jPD7XSdXsYruYYXGPUjh_ZdvY5OMW_3/view?usp=drive_link

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
Cumplido satisfactoriamente.
