### ISSUE TITLE
Mis tareas: que recupere las tareas de forma descendente

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#244]
Ambiente Test - v2.7.8

**Descripción:**
Al dirigirse a la bandeja de "Mis tareas" el sistema recupera el listado con un orden ASC y sería conveniente visualizar las tareas de forma inversa a la que se muestra actualmente por defecto.

**Resultado esperado:**
que el usuario visualice las tareas desde la más reciente a la tareas más antiguas

 

https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/8d15debd-a62c-47ec-9314-da486d4a12c5

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
