### ISSUE TITLE
Mantenimiento-->Plan de Mantenimiento-->Calendario: error al asignar la tarea al mantenedor

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#245]
Ambiente de DEMO - v2.7.8 

**Descripción:**
Al seleccionar asignar la tarea a un mantenedor el sistema muestra un cartel de Error" (ver imagen adjunta)

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/d0cc6406-a4a7-4636-9302-587e30b9af5c)

Luego, al dar clic en el botón "aceptar", al parecer se guarda el proceso, pero no recupera el nombre del usuario asignado "Mantenedor" en ninguna pantalla, como ejemplo se agrega la sieguiente imagen de la Bandeja de "Mis Tareas" 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/b09af416-9c01-46a7-afe2-d6cab4985ebc)

**Información adicional:** 
El user "Mantenedor" puede tomar la tarea pero el sistema no recupera su nombre en la pantalla de la "Confección del Informe de servicio"
_Similar al issue_ #139 

**Pasos a reproducir:**
_Previamente, cargar una Solicitud de servicio --> Asignarla como "Urgente"_
1. En "Plan de mantenimiento" clic en la solapa "Solicitud de servicio" 
2. Clic en el botón "Generar OT" -colocar una fecha y hs-
3. Clic en el botón "Aceptar"
4. Clic en la tarea que se encuentra en la fecha programada en el ítem anterior sobre el Calendario,
5. En la solapa "Asignación responsable", seleccionar un user del listado
6. Clic en el botón "Aceptar"

**Credenciales:**
URL: https://demo.cloudtrazalog.com/tools/traz-prod-assetplanner/
user: admin@novu.com / supman@novu.com / mantenedor@novu.com 
pass: 12345

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
