### ISSUE TITLE
Mis Tareas-->Entrega Ped. Materiales: quitar validación del formulario

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#246]
Ambiente Test - v2.7.8 | user: almacen1 | pass: 123
Ambiente Producción - v2.7.8 | user: almacen@test.com | pass: 12345

**Descripción:**
Al momento de realizar la entrega de materia prima, el sistema valida los campos requeridos del formulario. Lo que correspondería es que los campos del formulario dejen de ser obligatorios para completar la tarea en cuestión.

**Detalles adicionales:**
**Impacto:** irrelevante para el cliente que actualmente lo está utilizando

### **Nota:** se puede copiar desde la pantalla de Trazalog Tools, ya que en esta la validación no está condicionada por el formulario de datos.
 
https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/da48940e-73cb-45fd-986f-ef26979b3453

**Resultado esperado:**
Que la tarea solo involucre ingresar la cantidad a entregar y completar la entrega del material pedido, nada más. Por eso se pide que los campos enlistados a continuación, sean opcionales
* Nro de Comprobante; 
* Fecha entrega; 
* Recibe nombre y apellido; y 
* DNI

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
