### ISSUE TITLE
SOPORTE-->ABM Grupo: cargar formulario al editar o agregar nuevo grupo  

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#247]
Ambiente DEMO - V2.7.8
URL: https://demo.cloudtrazalog.com/tools/traz-prod-assetplanner/login
user: supman@novu.com
pass:12345

**Descripción:**
Al editar un Grupo o añadir uno Nuevo, se solicita agregar el formulario dinámico corto para una muestra con un potencial cliente, (ver imagen adjunta), 

en el menú de opciones, tanto de la ventana **Agregar Grupo** o **Editar Grupo** 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/3def6e15-e60d-4055-b440-2fe470034b77)

este formualario deberá poder verse desde la ventana del botón de acción "Mantenimiento Autónomo" y lanzar la solicitud de servicio. Se deja a modo de sugerencia uan imagen del formulario de "control topadora" 
(y en lo posible acortar el formulario).

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/36757994-4d0f-4654-839a-9d9734c3db4c)

**Pasos a reproducir:**
1. En ABM
2. Clic en ABM Grupos
3. Clic en el botón "Agregar"
4. Completar los campos obligatorios

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
