### ISSUE TITLE
SOPORTE-->Notificaciones: que el solicitante reciba las notificaciones en la instancia final "Prestar conformidad"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#248]
Ambiente DEMO - v2.7.8

**Descripción:**
Cuando el supervisor cierra la tarea llamada **Verificar Informe de Servicio** el proceso lanza una tarea a la bandeja de Mis Tareas del  _Solicitante,_ llamada "Prestar Conformidad" y el solicitante, actualmente, no recibe la notificación de dicha tarea. Lo correspondiente sería que el rol del solicitante reciba las notificaciones en la instancia final "Prestar conformidad".

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.9
