### ISSUE TITLE
Orden de las tareas con falta de optimización

### ISSUE THREAD

**Issue by fhernandez-trazalog** [Trazalog/traz-prod-assetplanner#250]
Ambient Test - v2.7.9
Ambiente Demo - v2.0.0?

**Descripción:**
Cuando el solicitante/supervisor crean una nueva solicitud de servicio, al ir luego el supervisor/planificador a la sección "Mis Tareas" es necesario ordenar con el filtro Id S.S. haciendo click dos veces, de modo de obtener un orden descendente de numeración de SS y así acceder a la que se acaba de crear. 

**Resultado esperado:** 
El orden natural en el que deberían aparecer por defecto las tareas, es cronológico inverso. Así se ordena las fechas empezando por lo más reciente y retrocediendo en el tiempo.

Ambient Test:
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/136350470/28b5a34e-d620-4043-8268-6a0a2ffbeaed)

Luego de filtrar dos veces por Id SS:
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/136350470/08fe6c19-7c51-4db9-a939-4bf49e5dbc8b)

Ambiente Demo:
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/136350470/1a1febce-3aff-414e-9f28-41cec01ced0f)

Luego de filtrar dos veces por Id SS:
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/136350470/73e68ef0-0b74-4d04-ac9e-3c71a6e6c230)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by fhernandez-trazalog** [comment]
Resuelto satisfactoriamente
