### ISSUE TITLE
SOPORTE-->Mantenimiento-->Solicitud de servicio: calcular la duración del "Tiempo de ciclo" de la tarea

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#252]
Ambiente Test - v2.8

**Descripción:**
Agregar una columna llamada "Tiempo de ciclo" en donde el sistema calcule la duración desde que se lanza la solicitud hasta que la finaliza el mantenedor

**Imagen de la ubicación de la columna en la tabla:**
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/a2df6138-0a6c-4691-96ad-d8add7adc558)

**Detalles adicionales:**
El "Tiempor de ciclo" será desde que el solicitante le da clic al botón "Guardar" que se indica en la imagen

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/67a96f11-053f-47ac-9848-c3fae8a6589b)

pasando por todo el circuito de:
* Analizar la tarea
* Planificar
* Asignar 
* Ejecutar OT 
Hasta que el mantenedor le da clic al botón "Terminar tarea" como se indica en la imagen

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/271e7548-6722-4eff-8273-47a55bd36c3d)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by fhernandez-trazalog** [comment]
Visualización del lapso de tiempo en solicitud de servicio: Está OK
