### ISSUE TITLE
SOPORTE-->Mantenimiento-->Solicitud de servicio: investigar Solicitud de servicio de ID - 5005

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#253]
Ambiente Producción - v2.8

**Descripción:**
La Solicitud de servicio Nro. 5005 se encuentra en estado de "Planificación", se la han asignado a un mantenedor y éste nunca recibió la tarea: "Ejecutar OT" 

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/fc3fc2b8-58f2-4dc5-8de7-8779626ca5a4)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
El desarrollador ha detectado que la solicitud se creo correctamente en la base y en bonita pero a nivel de base de datos no se creo la orden de trabajo asociada a esa solicitud

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/5a57c31c-6952-4f74-bbe8-cadf23da32ca)

**Comment by floto-trazalog** [comment]
Respondido al cliente.
No se ha guardado un orden de trabajo que esté asociada a dicha tarea,
