### ISSUE TITLE
Mis tareas-->Entrega Ped. Materiales: modificar el nombre del botón "Finalizar pedido"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#255]
Ambiente test - v2.8

**Descripción:**
Al seleccionar la tarea llamada "Entrega materiales" se recomienda cambiar el nombre del botón "Finalizar pedido" por _Finalizar pedido con entrega parcial_ 
se adjunta una imagen y en la misma se muestra un ejemplo de la modificación del botón
Él mismo se encuentra en Tools por lo que se podría obtener de allí

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/f6eb198f-f209-4cba-94a5-616d65673ae1)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.9
