### ISSUE TITLE
Escritorio: error al recuperar datos 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#256]
Ambiente test - v2.8

**Descripción:**
Al ingresar en el sistema con usuario y contraseña correctos se muestra el cartel de la imagen a continuación

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/c7791503-fd5d-468e-a11c-7d9461e797c9)

y luego, no recupera los datos para mostrar los gráficos correspondientes

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.9
