### ISSUE TITLE
Demoras: investigar y/o analizar maneras de disminuir lo máximo posible las demoras en las pantallas

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#257]
Ambiente Producción - v2.8

**Descripción:**
Al loguearse con el usuario planman, se inicia en la página de Escritorio, imagen que se muestra a continuación, el sistema se demora 1 minuto 29 segundos en completar

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/7c0666e2-5dc0-49ca-b53e-ad2e66dbd7a9)
Y luego, en la página de Mantenimiento-->Solicitudes de servicio, se demora 18 segundos

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/292b6be4-008f-483a-b9a1-428554f63526)

> **Detalles adicionales**

**Impacto**
La usabilidad del sistema para ciertos clientes, ocasiona frustración y retrasos en su tareas diarias

**Resultado esperado**
Que las demoras no superen los 8 segundos de tiempo de carga o en lo posible reducir el tiempo

**Evidencias tomadas con el cronómetro**

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/14ea81ef-78a6-46a1-af25-44a4175fc5b2)
![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/da3b0ee4-04ad-48d4-99c8-ad09e0d5c49c)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado
