### ISSUE TITLE
Mantenimiento-->Plan de mantenimiento: agregar una tabla de referencias en el front

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#263]
Ambiente Test - v2.8

**Descripción:**
Agregar en la vista de calendario, las **Referencias de colores**, en donde se indique el color de cada tarea (ver imagen)

![image](https://github.com/Trazalog/traz-prod-assetplanner/assets/88331456/8cb8d54b-c979-4365-8412-7a78f43ca607)

**Pasos a reproducir:**
1. En el menú _Mantenimiento_
2. Clic en _Plan de mantenimiento_

**Comment by focafunk** [comment]
hacerlo, ponerlo sobre calendario no ahi

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.9.1

**Comment by eaguirre-trazalog** [comment]
Funciona correctamente
Sugerencia: agregar el usuario con el que se realiza la prueba
