### ISSUE TITLE
Bandeja de Tareas: modificar el Nro de Id OT en un botón & recuperar los datos de la orden de trabajo  

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#267]
Ambiente test - v2.8

**Sugerencia:**
### 1) Funcionalidad de botón:
En la columna Id OT de la bandeja de tareas, se requiere que los Nros. de cada OT figuren con la funcionalidad de botón en donde se recuperen los datos de cada Orden de trabajo, se adjunta el video en el paso 3. 
**Nota:**
Consultar con Rodo, en el código se ha llamado bajo el nombre "bolita" o "pelotita"

### 2) Texto flotante:
Actualmente, al pasar el cursor sobre el Nro de Orden de trabajo recupera el texto _Null_ y lo correspondiente es que sea _Orden de trabajo_

![image](https://github.com/user-attachments/assets/e9669eac-644d-4f03-a024-d955109f67fe)

### 3) **Detalles adicionales** en el video

https://github.com/user-attachments/assets/c3152a4f-aa79-4297-b70f-40af76c4117d

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.9.1

**Comment by eaguirre-trazalog** [comment]
Probado con suptest1,mantest1,plantest1,solistest1
1 Funcionalidad del boton- Funciona correctamente 
2- Texto flotante: Funciona incorrectamente, actualmente muestra el numero de la columna Id OT cuando deberia mostrar el texto "Orden de trabajo". Por ejemplo si el numero es 2193 como se muestr a continuacion
![image](https://github.com/user-attachments/assets/bd42571f-8d62-45f1-b42f-2c6cb1fe174f)

**Comment by eaguirre-trazalog** [comment]
Probado con solman@test.com / supman@test.com / mantenedor@test.com / mantenedor2@test.com / almacen@test.com
En PROD
Aplican los mismos issues que en ambiente TEST
