### ISSUE TITLE
SOPORTE TICA-->MTTO-->Informe Servicios: investigar el guardado de las "Fechas Inicio/Fin Tareas"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#272]
Ambiente Producción - v2.3.10

**Descripción:**
Se han Ejecutado las ordenes de trabajo en la instancia de Tierras de Capayán y como se observa en el video de abajo los datos de las **Fechas Inicio/Fin tarea** se guardaron invertidos. 

https://github.com/user-attachments/assets/b4c9e37f-5b0c-4fce-ba37-97b8760b16dd

> **Datos adicionales:
Resultado esperado (1):** Entender por qué ha sucedido el defecto mencionado, anteriormente. 
Se solicita investigar los casos de las siguientes **Ordenes de Trabajo:**

_**Nota:** No se pudo reproducir en el ambiente de Test._

#OT
* 7414
* 7433
* 7241
* 7242

**Pasos a reproducir:**
1. En Mantenimiento
2. Clic en Informe de servicio
3. Clic en el botón de acción "Ver Informe"

---

Una vez aclarado el desperfecto...
**Resultado esperado (2):** 
* Que al iniciar y terminar la tarea, el sistema recupere en pantalla los datos correspondientes a la Fecha inicio tarea y a la Fecha fin tarea y;
* Que los datos de las OTs enumeradas arriba del issue figuren en su campo correspondiente.

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en Producción
