### ISSUE TITLE
SOPORTE>>TICA-->Mtto-->Plan de mantenimiento: que recupere los datos "Duración" y "Frec."

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#276]
Ambiente TEST - v2.9

**Descripción**:
Al crear uan tarea **Preventiva** y luego, para asignar la OT asociada, se puede ver que el sistema no recupera la "Duración" y "Frec." de la tarea y, lo correspondiente sería que figure en Duración = 1 y en Frec. = 7 _(son datos a modo de ejemplo)_

![image](https://github.com/user-attachments/assets/3f6e9365-aec3-40b4-ad72-4905f2fe6899)

Se deja el link del video explicativo, dar clic [aquí](https://drive.google.com/file/d/1IsDfvLFE3FkpVClAq9Io4NTnswV-tZTg/view?usp=drive_link)

**Pasos a seguir:**

1. Guardar una nueva tarea Preventiva
2. Ingresar al menú **Mantenimiento**-->**Plan de mantenimiento**
3. Planificar la OT asociada desde la solapa "Preventivo"
4. Completar los datos Fecha y hora de la OT
5. Clic en botón "Guardar"
6. Seleccionar dicha tarea en el calendario

**Comment by floto-trazalog** [comment]
Solucionado en v2.9.1

**Comment by eaguirre-trazalog** [comment]
Probado con suptest1
Funciona correctamente

**Comment by eaguirre-trazalog** [comment]
Probado con [solman@test.com] / [supman@test.com] en produccion
Funciona correctamente
