### ISSUE TITLE
SOPORTE>>TICA-->Mtto-->Plan de mantenimiento: eliminar las OT`s del calendario

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#278]
Ambiente Producción - v2.9

**Solicitud:**
El cliente solicita borrar **los preventivos**, es decir, las Ordenes de Trabajo que están cargadas en el plan de mantenimiento, ya que fueron realizadas a modo de práctica, para poder empezar a cargar los preventivos de los cronogramas que van a estar. 

* OT: 7518/7519 / 7521
* OT: 7559 (es la única OT que se ha commpletado el circuito)-->Se deja una imagen al final del issue
* OT: desde la Nro. 7588 a 7602

![image](https://github.com/user-attachments/assets/28227b0d-eee2-4ea8-a00f-aaffb98068cc)

![Captura de pantalla 2024-09-03 155934](https://github.com/user-attachments/assets/e06a3351-5edc-4bcb-9409-117a025883a5)

![Captura de pantalla 2024-09-03 155946](https://github.com/user-attachments/assets/d2f4b8a0-78b9-4434-8ed1-86c9728be644)

![Captura de pantalla 2024-09-03 155958](https://github.com/user-attachments/assets/f5dedc3e-10d7-459b-8c9e-68520cce2650)

![image](https://github.com/user-attachments/assets/a8485908-4856-4bf8-a53a-b20b389ccab0)

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.9
