### ISSUE TITLE
Mantenimiento-->Preventivos-->Agregar: el campo de Sector no está validando & al filtrar Equipo por Sector no limpia el campo 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#40]
Ambiente Test - v2.4.12

**Descripción:**
### Bug:
Al ingresar un Sector inexistente, el sistema permite ingresar cualquier nombre sin validar si este pertenece a la empresa en cuestión.
Correspondería que el programa avise al usuario con un alert de error para que ingrese un dato correcto.

### Sugerencia:
Al filtrar un Equipo por Sector y luego cambiar dicho Sector el sistema no limpia el campo de Equipo, el cual debería limpiarse al modificar el campo del sector

https://user-images.githubusercontent.com/88331456/158843651-f8ef2a84-affd-4697-8e2b-598ec03b1632.mp4

**Pasos a reproducir:**

1. En el menú Mantenimiento
2. Dar click en la pestaña de Preventivo
3. Dar click en el botón "Agregar"
4. Ingresar cualquier dato en el campo "Sector"
5. Dar click en el menú desplegable de "Equipos"

**Comment by fhernandez-trazalog** [comment]
Solucionado
