### ISSUE TITLE
Mantenimiento-->Equipo: al agregar nuevo, que permita adjuntar al menos 5 archivos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#66]
Ambiente test - v2.5

**Descripción:**
Al clickear el botón "Adjuntar archivo" el sistema solo permite agregar un archivo por equipo. Lo correspondiente sería que agregué al menos 5 archivos

![image](https://user-images.githubusercontent.com/88331456/212759296-10b57002-ec00-47c1-be77-94f1c69884cd.png)

**Comment by fhernandez-trazalog** [comment]
Me permitió adjuntar 1, 6 e incluso 12 archivos.

**Comment by floto-trazalog** [comment]
Solucionado en TEST - v2.6.4
