### ISSUE TITLE
SOPORTE-->Almacenes-->Artículo: que se guarden los datos al editar los campos

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-assetplanner#69]
Ambiente test - 2.5

**Descripción**
Al editar un artículo el sistema no recupera los datos cargados previamente del formulario, cuando lo correspondiente es que recupere los datos y permita modificar los campos

https://user-images.githubusercontent.com/88331456/212764609-af4af8ef-4bd4-4d6a-9788-2ddc8df5f691.mp4

**Comment by jfernandez-trazalog** [comment]
Roge Sanchez.

**Comment by floto-trazalog** [comment]
Solucionado en v2.7.8
